name: Deploy

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: falkensteink/ci-templates/.github/workflows/toshi-deploy.yml@main
    with:
      repo-name: BirdMug-Portal
      branch: main
    secrets:
      TOSHI_DEPLOY_SECRET: ${{ secrets.TOSHI_DEPLOY_SECRET }}
